### ISSUE TITLE
BraketAwsQubitDevice unnecessarily computes parameter-shifted gradients for SV1.

### ISSUE THREAD

**Issue by kshyatt-aws** [amazon-braket/amazon-braket-pennylane-plugin-python#223] opened 2024-01-17 22:24 UTC
**Describe the bug**

Consider a circuit like:
```
sv1_device_arn = "arn:aws:braket:::device/quantum-simulator/amazon/sv1"
dm1_device_arn = "arn:aws:braket:::device/quantum-simulator/amazon/dm1"
dev = qml.device("braket.aws.qubit", device_arn=sv1_device_arn, wires=nqubits)
nqubits = 4
@qml.qnode(dev)
def quantum_circuit(input, weights):
    # Prepare circuit here
    for i in range(nqubits):
        qml.H(i)
    # Measurement layer
    return [qml.expval(qml.PauliZ(i)) for i in range(nqubits)]
```
When SV1 is used, [this line](https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/blob/main/src/braket/pennylane_plugin/braket_device.py#L849) is triggered. This will compute parameter-shifted derivatives *even on the forward pass*, when they should not be computed. This makes running with SV1 ~10x slower (and incurs extra costs) compared to DM1.

**To reproduce**
Run above code snippet.

**Expected behavior**
The Braket-PL device should only compute the gradient if it's "really" requested.

**Screenshots or logs**
N/A

**System information**
A description of your system. Please provide:
- **Amazon Braket Python PennyLane Plugin version**: 1.23.0
- **Amazon Braket Python SDK version**: 1.66.0
- **Amazon Braket Python Schemas version**: N/A
- **Amazon Braket Python Default Simulator version**: N/A
- **Python version**: 3.9

**Additional context**
One other solution would be to avoid calling `execute_and_gradients` entirely in this case.

**Comment by speller26** [comment] 2024-01-18 00:51
Did not intend to auto-close the issue

**Comment by laurencap** [comment] 2024-01-29 19:07
@kshyatt-aws confirmed with me that we can close the issue, since any additional work would be outside this repo. Thanks!

**Closed by laurencap** 2024-01-29 19:07 UTC
Labels: bug
